blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_publish,)

app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<int:pk>/", cache_page(60)(BlogDetailView.as_view()), name="blog_view"),
    path("update/<int:pk>", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>", BlogDeleteView.as_view(), name="blog_delete"),
    path("publish/<int:pk>", toggle_publish, name="toggle_publish"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include(('main_app.urls', 'main_app'), namespace='main_app')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path

from main_app.apps import MainAppConfig

from main_app.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MailingSetupListView, MailingSetupDetailView, MailingSetupUpdateView, MailingSetupCreateView, \
    MailingSetupDeleteView, MailingMessageListView, MailingMessageDetailView, MailingMessageCreateView, \
    MailingMessageUpdateView, MailingMessageDeleteView, LogListView, home

app_name = MainAppConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('client/', ClientListView.as_view(), name='client_list'),
    path('main_app/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
    path('update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing/', MailingSetupListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>', MailingSetupDetailView.as_view(), name='mailing_detail'),
    path('mailing/create/', MailingSetupCreateView.as_view(), name='mailing_create'),
    path('mailing/update/<int:pk>', MailingSetupUpdateView.as_view(), name='mailing_update'),
    path('mailing/delete/<int:pk>', MailingSetupDeleteView.as_view(), name='mailing_delete'),
    path('message/', MailingMessageListView.as_view(), name='message_list'),
    path('message/<int:pk>', MailingMessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MailingMessageCreateView.as_view(), name='message_create'),
    path('message/update/<int:pk>', MailingMessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>', MailingMessageDeleteView.as_view(), name='message_delete'),
    path('log/', LogListView.as_view(), name='log_list'),
]

main_app/models.py
from django.db import models

from config.settings import NULLABLE
from users.models import User


class Client(models.Model):
    first_name = models.CharField(
       max_length=50,
       verbose_name="Имя клиента",
       help_text="Введите имя",
    )
    midl_name = models.CharField(
        max_length=50,
        verbose_name="Отчество клиента",
        help_text="Введите отчество",
        **NULLABLE,
    )
    last_name = models.CharField(
        max_length=50,
        verbose_name="Фамилия клиента",
        help_text="Введите фамилию",
    )
    email = models.EmailField(
        max_length=150,
        verbose_name="Email клиента",
        help_text="Введите контактный email",
    )
    comment = models.TextField(
        verbose_name="Коментарий",
        help_text="Введите коментарий",
        ** NULLABLE,
    )
    owner = models.ForeignKey(
        User,
        verbose_name='Владелец',
        on_delete=models.SET_NULL,
        **NULLABLE
    )

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ('last_name',)

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class MailingSetup(models.Model):
    PERIODS = (
        ("once", 'Единоразовая'),
        ("daily", 'Ежедневная'),
        ("weekly", 'Раз в неделю'),
        ("monthly", 'Раз в месяц'),
    )
    STATUSES = (
        ("created", 'Создана'),
        ("started", 'Запущена'),
        ("finished", 'Завершена'),
    )
    start = models.DateTimeField(
        verbose_name="Дата начала первой рассылки",
    )
    next_send = models.DateTimeField(
        **NULLABLE,
        verbose_name="Дата следующей отправки",
    )
    periodicity = models.CharField(
        verbose_name="Переодичность рассылки",
        choices=PERIODS,
        default="once",
    )
    status = models.CharField(
        verbose_name="Статус рассылки",
        choices=STATUSES,
        default="created",
    )
    clients = models.ManyToManyField(
        Client,
        related_name="Clients",
    )
    message = models.ForeignKey(
        "MailingMessage",
        related_name="messages",
        on_delete=models.SET_NULL,
        verbose_name="Сообщение рассылки",
        null=True
    )
    owner = models.ForeignKey(
        User,
        verbose_name='Владелец',
        on_delete=models.SET_NULL,
        **NULLABLE
    )
    is_published = models.BooleanField(
        default=True,
        verbose_name="Опубликовано",
        help_text="Отметьте для активации"
    )

    class Meta:
        verbose_name = "Настройка рассылки"
        verbose_name_plural = "Настройки рассылок"
        ordering = ('start',)
        permissions = [
            ("block_user", "Can block user"),
            ("disable_mailings", "Can disable mailings"),
        ]

    def __str__(self):
        return f'Рассылка {self.periodicity}. Дата начала: {self.start}. Статус: {self.status}'


class MailingMessage(models.Model):
    topic = models.CharField(
        max_length=300,
        verbose_name="Тема рассылки",
        help_text="Введите тему рассылки",
    )
    body = models.TextField(
        verbose_name="Содержание рассылки",
    )
    owner = models.ForeignKey(
        User,
        verbose_name='Владелец',
        on_delete=models.SET_NULL,
        **NULLABLE
    )

    class Meta:
        verbose_name = "Сообщение рассылки"
        verbose_name_plural = "Сообщения рассылок"
        ordering = ('topic',)

    def __str__(self):
        return f'{self.topic}'


class Log(models.Model):
    STATUS_LOG = (
        ("success", "успешно"),
        ("unsuccess", "неуспешно")
    )

    time = models.DateTimeField(
        verbose_name="Дата и время попытки отправки", auto_now_add=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_LOG,
        verbose_name='Cтатус рассылки'
    )
    server_response = models.CharField(
        max_length=150,
        verbose_name="Ответ сервера почтового сервиса",
        **NULLABLE
    )
    mailing = models.ForeignKey(
        MailingSetup,
        on_delete=models.CASCADE,
        verbose_name="Рассылка"
    )
    client = models.ForeignKey(
        Client,
        on_delete=models.CASCADE,
        verbose_name="клиент",
        **NULLABLE
    )

    def __str__(self):
        return f"{self.mailing} {self.time} {self.status} {self.server_response}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылок"

main_app/forms.py
from django.forms import BooleanField, ModelForm
from django import forms

from main_app.models import Client, MailingSetup, MailingMessage


class StileFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ClientForm(StileFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ("owner",)


class MailingSetupForm(StileFormMixin, ModelForm):
    class Meta:
        model = MailingSetup
        exclude = ('owner',)
        widgets = {
            "start": forms.DateInput(
                format="%Y-%m-%d %H:%M:%S",
                attrs={
                    "class": "form-control",
                    "placeholder": "Select a date",
                    "type": "datetime-local",
                },
            ),
        }


class MailingMessageForm(StileFormMixin, ModelForm):
    class Meta:
        model = MailingMessage
        exclude = ("owner",)

main_app/views.py
from django.conf import settings

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from django.shortcuts import render

from django.core.cache import cache

from blog.models import Blog
from main_app.forms import ClientForm, MailingSetupForm, MailingMessageForm
from main_app.models import Client, MailingSetup, MailingMessage, Log


def home(request):
    # Низкоуровневое кеширование данных на Главной странице
    if settings.CACHE_ENABLED:
        key_blogs = f'key_blogs_{Blog.objects.filter(is_published=True)}'
        key_mailings = f'key_mailings_{MailingSetup.objects.all()}'
        key_mailings_is_published = f'key_mailings_is_published_{MailingSetup.objects.filter(is_published=True)}'
        key_clients = f'key_clients_{Client.objects.values('email').distinct()}'

        # Получаем данные по ключу
        blogs = cache.get(key_blogs)
        mailings = cache.get(key_mailings)
        mailings_is_published = cache.get(key_mailings_is_published)
        clients = cache.get(key_clients)

        if blogs is None or mailings is None or mailings_is_published is None or clients is None:
            blogs = Blog.objects.filter(is_published=True)
            mailings = MailingSetup.objects.all()
            mailings_is_published = MailingSetup.objects.filter(is_published=True)
            clients = Client.objects.values('email').distinct()

            # Записываем данные с ключем
            cache.set(key_blogs, blogs)
            cache.set(key_mailings, mailings)
            cache.set(key_mailings_is_published, mailings_is_published)
            cache.set(key_clients, clients)

    else:
        # Если кеширование выключено, получаем данные с базы
        blogs = Blog.objects.filter(is_published=True)
        mailings = MailingSetup.objects.all()
        mailings_is_published = MailingSetup.objects.filter(is_published=True)
        clients = Client.objects.values('email').distinct()

    context = {
        'blog_list': blogs.order_by('?')[:3],
        'mailings_list': mailings,
        'mailings_is_published': mailings_is_published,
        'clients_list': clients
    }

    return render(request, 'main_app/home.html', context)


class ClientListView(ListView):
    model = Client


class ClientDetailView(DetailView):
    model = Client


class ClientCreateView(CreateView, LoginRequiredMixin):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("main_app:client_list")

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()

        return super().form_valid(form)


class ClientUpdateView(UpdateView, LoginRequiredMixin):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("main_app:client_list")


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy("main_app:client_list")


class MailingSetupListView(ListView):
    model = MailingSetup


class MailingSetupDetailView(DetailView):
    model = MailingSetup


class MailingSetupCreateView(CreateView, LoginRequiredMixin):
    model = MailingSetup
    form_class = MailingSetupForm
    success_url = reverse_lazy("main_app:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()

        return super().form_valid(form)


class MailingSetupUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingSetup
    form_class = MailingSetupForm
    success_url = reverse_lazy("main_app:mailing_list")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return super().get_form_class()
        raise PermissionDenied


class MailingSetupDeleteView(DeleteView):
    model = MailingSetup
    success_url = reverse_lazy("main_app:mailing_list")


class MailingMessageListView(ListView):
    model = MailingMessage


class MailingMessageDetailView(DetailView):
    model = MailingMessage


class MailingMessageCreateView(CreateView, LoginRequiredMixin):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy("main_app:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()

        return super().form_valid(form)


class MailingMessageUpdateView(UpdateView, LoginRequiredMixin):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy("main_app:message_list")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return MailingMessageForm
        raise PermissionDenied


class MailingMessageDeleteView(DeleteView):
    model = MailingMessage
    success_url = reverse_lazy("main_app:message_list")


class LogListView(ListView):
    model = Log

main_app/templates/main_app/client_confirm_delete.html
{% extends 'main_app/index.html'%}
{% block content %}
<div class="container py-4">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card-header py-2">
                <p>Вы действительно хотите удалить клиента:
                {{ client.last_name }}
                {{ client.first_name }}
                E-mail:
                {{ client.email }}
                </p>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" role="button">Подтвердить</button>
                <a href="{% url 'main_app:client_list' %}" type="button" class="btn btn-link">Отменить</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

main_app/templates/main_app/client_detail.html
{% extends 'main_app/index.html'%}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row col-8">
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">
                ФИО клиента:
                {{ client.last_name }}
                {{ client.first_name }}
                {{ client.midl_name }}
              </p>
              <p class="card-text">
                E-mail клиента:
                {{ client.email }}
              </p>
              <p class="card-text">
                Коментарий:
                {{ client.comment }}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main_app:client_list' %}" type="button" class="btn btn-link">Назад</a>
                  {% if request.user == object.owner %}
                  <a href="{% url 'main_app:client_update' client.pk %}" type="button" class="btn btn-link">Редактировать</a>
                  <a href="{% url 'main_app:client_delete' client.pk %}" type="button" class="btn btn-link">Удалить</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/client_form.html
{% extends 'main_app/index.html'%}
{% block content %}
<div class="container py-4">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card-header py-2">
                {% if object %}
                    <h3 class="card-text">Редектирование карточки клиента</h3>
                {% else %}
                    <h3 class="card-text">Добавление клиента</h3>
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="btn-group col-3" >
                    <button type="submit" class="btn btn-primary" role="button">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </div>
                <a href="{% url 'main_app:client_list' %}" type="button" class="btn btn-link">Назад</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

main_app/templates/main_app/client_list.html
{% extends 'main_app/index.html'%}
{% block content %}
    <div class="container">
      {% for client in object_list %}
      {% if client.owner == user or user.is_superuser %}
        <div class="row mb-3 text-left">
          <div class="col-2 themed-grid-col">
            {{ client.id }}
          </div>
          <div class="col-4 themed-grid-col">
            Клиент:
            {{ client.last_name }}
            {{ client.first_name }}
          </div>
          <div class="col-2 themed-grid-col">
            E-mail:
            {{ client.email|truncatechars:5 }}@...
          </div>
          <div class="col-4 themed-grid-col">
            <a href="{% url 'main_app:client_detail' client.pk %}" class="icon-link">Подробнее</a>
            {% if request.user == object.owner %}
            <a href="{% url 'main_app:client_update' client.pk %}" class="icon-link">Редактировать</a>
            <a href="{% url 'main_app:client_delete' client.pk %}" class="icon-link">Удалить</a>
            {% endif %}
          </div>
        </div>
      {% endif %}
      {% endfor %}
    </div>
{% endblock %}

main_app/templates/main_app/home.html
{% extends 'main_app/index.html' %}
{% load my_tags %}
{% block content %}
{% if user.is_authenticated %}
  <div class="p-2 rounded-4 col-12 my-2 border">
      <div class="list-group list-group-flush container p-2 my-2">
          <h5 class="mx-3 my-2 text-secondary">Добро пожаловать, {{ request.user }}</h5>
          <a class="list-group-item list-group-item-action" aria-current="true">
              <b>Ваши рассылки</b> <span class="badge text-bg-primary rounded-pill mx-3"> {{ mailings_list.count }}</span>
          </a>
          <a class="list-group-item list-group-item-action" aria-current="true">
              <b>Активные рассылки</b> <span class="badge text-bg-primary rounded-pill mx-3"> {{ mailings_is_published.count }}</span>
          </a>
          <a class="list-group-item list-group-item-action" aria-current="true">
              <b>Ваши клиенты</b> <span class="badge text-bg-primary rounded-pill mx-3"> {{ clients_list.count }}</span>
          </a>
      </div>
  </div>

{% else %}

  <div class="container px-4 py-5" id="featured-3">
    <h2 class="pb-2 border-bottom">Преимущества нашего сервиса</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
      <div class="feature col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#collection"/></svg>
        </div>
        <h3 class="fs-2 text-body-emphasis">Легко хранить</h3>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      </div>
      <div class="feature col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#people-circle"/></svg>
        </div>
        <h3 class="fs-2 text-body-emphasis">Легко добавлять</h3>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      </div>
      <div class="feature col">
        <div class="feature-icon d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-2 mb-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"/></svg>
        </div>
        <h3 class="fs-2 text-body-emphasis">Легко настраивать</h3>
        <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
      </div>
    </div>
  </div>

{% endif %}

<div class="b-example-divider"></div>

<div class="p-2 rounded-4 col-12 my-4 shadow text-center">
      <h3 class="mx-3 my-2">Блог</h3>
</div>
<div class="container mt-3 mb-3">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in blog_list %}
            <div class="col">
              <div class="card shadow-sm">
                  <img src="{{ object.image | media_filter }}">
                  <div class="card-body">
                      <p class="card-text">{{ object.title }}</p>
                      <p class="card-text">{{ object.content | truncatechars:100 }}</p>
                      <p class="card-text">{{ object.created_at }}</p>
                      <a href="{% url 'blog:blog_view' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Подробнее</a>
                  </div>
              </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main_app/templates/main_app/log_list.html
{% extends 'main_app/index.html'%}
{% block content %}
<div class="container">
    <section class="jumbotron text-center">
    <div class="container">
        <h3 class="jumbotron-heading">Отчет о попытках рассылок</h3>
    </div>
    </section>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Рассылка</th>
            <th scope="col">Время</th>
            <th scope="col">Статус</th>
            <th scope="col">Ответ сервера</th>
        </tr>
        </thead>
        <tbody>
        {% for log in object_list %}
        <tr>
            <td>{{ log.mailing }}</td>
            <td>{{ log.time }}</td>
            <td>{{ log.status }}</td>
            <td>{{ log.server_response }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

main_app/templates/main_app/mailingmessage_confirm_delete.html
{% extends 'main_app/index.html'%}
{% block content %}
<div class="container py-4">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card-header py-2">
                <p>Вы действительно хотите удалить сообщение рассылки:
                {{ object.topic }}
                </p>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" role="button">Подтвердить</button>
                <a href="{% url 'main_app:message_list' %}" type="button" class="btn btn-link">Отменить</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

main_app/templates/main_app/mailingmessage_detail.html
{% extends 'main_app/index.html'%}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row col-8">
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">
                Тема рассылки:
                {{ object.topic }}
              </p>
              <p class="card-text">
                Содержание рассылки:
                {{ object.body }}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main_app:message_list' %}" type="button" class="btn btn-link">Назад</a>
                  {% if request.user == object.owner %}
                  <a href="{% url 'main_app:message_update' object.pk %}" type="button" class="btn btn-link">Редактировать</a>
                  <a href="{% url 'main_app:message_delete' object.pk %}" type="button" class="btn btn-link">Удалить</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/mailingmessage_form.html
{% extends 'main_app/index.html'%}
{% block content %}
<div class="container py-4">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card-header py-2">
                {% if object %}
                    <h4 class="card-text">Редектирование сообщения рассылки: {{ object.message.topic }}</h4>
                {% else %}
                    <h4 class="card-text">Добавление сообщения рассылки</h4>
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="btn-group col-3" >
                    <button type="submit" class="btn btn-primary" role="button">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </div>
                <a href="{% url 'main_app:message_list' %}" type="button" class="btn btn-link">Назад</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

main_app/templates/main_app/mailingsetup_confirm_delete.html
{% extends 'main_app/index.html'%}
{% block content %}
<div class="container py-4">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card-header py-2">
                <p>Вы действительно хотите удалить рассылку:
                {{ object.message.topic }}
                </p>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" role="button">Подтвердить</button>
                <a href="{% url 'main_app:mailing_list' %}" type="button" class="btn btn-link">Отменить</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

main_app/templates/main_app/mailingsetup_detail.html
{% extends 'main_app/index.html'%}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row col-8">
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">
                Название рассылки:
                {{ object.message.topic }}
              </p>
              <p class="card-text">
                Начало рассылки:
                {{ object.start }}
              </p>
              <p class="card-text">
                Переодичность:
                {{ object.periodicity }}
              </p>
              <p class="card-text">
                Статус:
                {{ object.status }}
              </p>
              <p class="card-text">
                Клиенты:
              </p>
              {% for client in object.clients.all %}
                <p class="card-text"> {{ client.email }}</p>
              {% endfor %}

              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'main_app:mailing_list' %}" type="button" class="btn btn-link">Назад</a>
                  {% if request.user == object.owner %}
                  <a href="{% url 'main_app:mailing_update' object.pk %}" type="button" class="btn btn-link">Редактировать</a>
                  <a href="{% url 'main_app:mailing_delete' object.pk %}" type="button" class="btn btn-link">Удалить</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/mailingsetup_form.html
{% extends 'main_app/index.html'%}
{% block content %}
<div class="container py-4">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card-header py-2">
                {% if object %}
                    <h4 class="card-text">Редектирование рассылки: {{ object.message.topic }}</h4>
                {% else %}
                    <h4 class="card-text">Добавление рассылки</h4>
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="btn-group col-3" >
                    <button type="submit" class="btn btn-primary" role="button">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </div>
                <a href="{% url 'main_app:mailing_list' %}" type="button" class="btn btn-link">Назад</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

main_app/templates/main_app/mailingsetup_list.html
{% extends 'main_app/index.html'%}
{% block content %}
    <div class="container">
      {% for object in object_list %}
      <div class="row mb-3 text-left">
        <div class="col-1 themed-grid-col">
          {{ object.id }}
        </div>
        <div class="col-2 themed-grid-col">
          {{ object.message.topic }}
        </div>
          <div class="col-4 themed-grid-col">
          Начало рассылки:
          {{ object.start }}
        </div>
        <div class="col-3 themed-grid-col">
          <a href="{% url 'main_app:mailing_detail' object.pk %}" class="icon-link">Подробнее</a>
          {% if request.user == object.owner %}
          <a href="{% url 'main_app:mailing_update' object.pk %}" class="icon-link">Редактировать</a>
          <a href="{% url 'main_app:mailing_delete' object.pk %}" class="icon-link">Удалить</a>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
{% endblock %}